<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Cirreum.Persistence</RootNamespace>
		<Description>SqlServer persistence provider for Cirreum framework</Description>
		<PackageTags>persistence,sqlserver,azure</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Cirreum.Persistence.Sql" Version="1.0.12" />
		<PackageReference Include="Cirreum.ServiceProvider" Version="1.0.21" />
		<PackageReference Include="Cirreum.Domain" Version="1.2.1" />
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="Dapper" Version="2.1.79" />
	</ItemGroup>

	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

</Project>
